import { INodeProperties } from 'n8n-workflow';

import { buildTickerProperty } from './Common.description';

export const historyOperation: INodeProperties = {
	displayName: 'Operation',
	name: 'operation',
	type: 'options',
	noDataExpression: true,
	displayOptions: { show: { resource: ['history'] } },
	options: [
		{
			name: 'Get Cashflows',
			value: 'getCashflows',
			description: 'Get cash movement history',
			action: 'Get cashflows',
		},
		{
			name: 'Get Orders',
			value: 'getOrders',
			description: 'Get orders history',
			action: 'Get orders history',
		},
		{
			name: 'Get Trades',
			value: 'getTrades',
			description: 'Get trades history',
			action: 'Get trades history',
		},
	],
	default: 'getOrders',
};

export const historyFields: INodeProperties[] = [
	{
		displayName: 'From',
		name: 'from',
		type: 'dateTime',
		displayOptions: { show: { resource: ['history'], operation: ['getOrders', 'getTrades'] } },
		default: '',
		required: true,
	},
	{
		displayName: 'Till',
		name: 'till',
		type: 'dateTime',
		displayOptions: { show: { resource: ['history'], operation: ['getOrders', 'getTrades'] } },
		default: '',
		required: true,
	},
	buildTickerProperty('history', ['getTrades'], {
		description: 'Optional ticker filter (e.g. AAPL.US)',
	}),
	{
		displayName: 'Trade ID',
		name: 'tradeId',
		type: 'number',
		displayOptions: { show: { resource: ['history'], operation: ['getTrades'] } },
		default: 0,
		description: 'Trade ID to start from',
	},
	{
		displayName: 'Max Results',
		name: 'maxResults',
		type: 'number',
		displayOptions: { show: { resource: ['history'], operation: ['getTrades'] } },
		default: 100,
		description: 'Max number of trades to return',
	},
	{
		displayName: 'Currency',
		name: 'currency',
		type: 'string',
		displayOptions: { show: { resource: ['history'], operation: ['getTrades'] } },
		default: '',
		description: 'Filter by currency',
	},
	{
		displayName: 'Reception ID',
		name: 'receptionId',
		type: 'number',
		displayOptions: { show: { resource: ['history'], operation: ['getTrades'] } },
		default: 0,
		description: 'Filter by office/reception ID',
	},
	{
		displayName: 'User ID',
		name: 'userId',
		type: 'number',
		displayOptions: { show: { resource: ['history'], operation: ['getCashflows'] } },
		default: 0,
	},
	{
		displayName: 'Group By Type',
		name: 'groupByType',
		type: 'boolean',
		displayOptions: { show: { resource: ['history'], operation: ['getCashflows'] } },
		default: false,
		description: 'Whether to group results by type',
	},
	{
		displayName: 'Cash Totals',
		name: 'cashTotals',
		type: 'boolean',
		displayOptions: { show: { resource: ['history'], operation: ['getCashflows'] } },
		default: false,
		description: 'Whether to include cash totals',
	},
	{
		displayName: 'Hide Limits',
		name: 'hideLimits',
		type: 'boolean',
		displayOptions: { show: { resource: ['history'], operation: ['getCashflows'] } },
		default: false,
		description: 'Whether to hide the limits block',
	},
	{
		displayName: 'Without Refund',
		name: 'withoutRefund',
		type: 'boolean',
		displayOptions: { show: { resource: ['history'], operation: ['getCashflows'] } },
		default: false,
		description: 'Whether to exclude refunds',
	},
	{
		displayName: 'Take',
		name: 'take',
		type: 'number',
		displayOptions: { show: { resource: ['history'], operation: ['getCashflows'] } },
		default: 50,
	},
	{
		displayName: 'Skip',
		name: 'skip',
		type: 'number',
		displayOptions: { show: { resource: ['history'], operation: ['getCashflows'] } },
		default: 0,
	},
	{
		displayName: 'Filters (JSON)',
		name: 'filtersJson',
		type: 'string',
		displayOptions: { show: { resource: ['history'], operation: ['getCashflows'] } },
		default: '[]',
		description: 'Filters array as JSON',
	},
	{
		displayName: 'Sort (JSON)',
		name: 'sortJson',
		type: 'string',
		displayOptions: { show: { resource: ['history'], operation: ['getCashflows'] } },
		default: '[]',
		description: 'Sort spec array as JSON',
	},
];
